### ISSUE TITLE
[meta] add GitPod configuration

### ISSUE THREAD

**Issue by Decipher** [contentacms/contenta_jsonapi#411]
**Is your feature request related to a problem? Please describe.**
As a contributor I want GitPod integration so I can contribute to this project without having to setup an environment.

**Describe the solution you'd like**
- [ ] Add GitPod config
- [ ] Add pre-build tasks
  - [ ] Setup development environment
  - [ ] Install dependencies
  - [ ] ...
- [ ] Add VS code extensions

**Additional context**
- https://drupalpod.com
- https://www.gitpod.io/docs/config-gitpod-file
- https://github.com/druxt/druxt.js/blob/develop/.gitpod.yml
